### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by menmarc** [StatCan/shiny#2]
Our shiny report under visualize-team/example2 uses two packages that aren't installed on the shiny server. 

Can you add them to your packages file?

sqldf
shinythemes

Thanks!

**Comment by blairdrummond** [comment]
On it.

**Comment by blairdrummond** [comment]
Oh. Can you reopen your PR? The issue you saw is just a defect of our CD scripts. Your changes were fine.

**Comment by menmarc** [comment]
sure I can reopen my PR

**Comment by blairdrummond** [comment]
FYI, your app works now
