### ISSUE TITLE
CD doesn't update the deployment image?

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/shiny#3]
I updated the image but noticed that the shiny deployment doesn't switch to the new image. Even when I manually restarted the deployment it didn't switch (still using the old sha).

How would I do this manually (until such a time as we integrate it into the CD) ?

**Comment by sylus** [comment]
Hey if okay this should always be done with a P.R. so can always get a +1 from someone as is a live service before gets merged. 

The CD atm only deploys for Shiny when is a stable tag release that has been published.

**Comment by sylus** [comment]
@zachomedia @justbert

**Comment by blairdrummond** [comment]
Ok sure thing; will make sure to always go through a PR.

I think issue #2 is still affected until the server is updated. @menmark . I'm off my machine now, but tomorrow morning I should just tag this as release then he should be good to go?

-------- Original Message --------
On Apr 28, 2020, 11:18 PM, William H < notifications@github.com> wrote:
Hey if okay this should always be done with a P.R. so can always get a +1 from someone as is a live service before gets merged.
The CD atm only deploys for Shiny when is a stable tag release that has been published.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[https://github.com](<a href=)/StatCan/shiny/issues/3#issuecomment-620968339">https://github.com/StatCan/shiny/issues/3#issuecomment-620968339", "url": "[https://github.com](<a href=)/StatCan/shiny/issues/3#issuecomment-620968339">https://github.com/StatCan/shiny/issues/3#issuecomment-620968339", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by zachomedia** [comment]
@blairdrummond Can you check now? I've created and published a release of the repo which triggered a deployment

**Comment by blairdrummond** [comment]
Working now!
